name: project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^10.0.0
  http: ^1.4.0
  intl: ^0.18.0
  image_picker: ^0.8.7+4
  geolocator: ^11.0.0
  firebase_core: ^3.13.0
  get_it: ^8.0.3
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  google_sign_in: ^6.3.0
  flutter_facebook_auth: ^6.0.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/